name: Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run linter
        run: yarn lint

      - name: Run tests
        run: yarn test

  build-android:
    name: Build Android App
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: Build Android Release
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Sign Android Release
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Upload Android Release
        uses: actions/upload-artifact@v3
        with:
          name: android-release
          path: ${{ steps.sign_app.outputs.signedReleaseFile }}

  build-ios:
    name: Build iOS App
    runs-on: macos-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      - name: Build iOS Release
        run: |
          cd ios
          xcodebuild -workspace QuackBrowser.xcworkspace -scheme QuackBrowser -configuration Release -sdk iphoneos -archivePath $RUNNER_TEMP/QuackBrowser.xcarchive clean archive
          xcodebuild -exportArchive -archivePath $RUNNER_TEMP/QuackBrowser.xcarchive -exportOptionsPlist ios/ExportOptions.plist -exportPath $RUNNER_TEMP/build

      - name: Upload iOS Release
        uses: actions/upload-artifact@v3
        with:
          name: ios-release
          path: $RUNNER_TEMP/build/*.ipa

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build-android, build-ios]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Android Release
        uses: actions/download-artifact@v3
        with:
          name: android-release
          path: releases/android

      - name: Download iOS Release
        uses: actions/download-artifact@v3
        with:
          name: ios-release
          path: releases/ios

      - name: Get Version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: QuackBrowser v${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          files: |
            releases/android/*.apk
            releases/ios/*.ipa
          body: |
            # QuackBrowser v${{ steps.get_version.outputs.VERSION }}
            
            ## What's New
            
            - Feature: New features in this release
            - Improvement: Performance improvements
            - Fix: Bug fixes
            
            ## Installation
            
            ### Android
            - Download the APK and install it directly on your device
            
            ### iOS
            - Please use TestFlight for iOS distribution 